# Generated by Django 5.0.4 on 2026-03-19 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField()),
                ('peso', models.FloatField(help_text='Proporção histórica de questões (soma dos pesos da trilha = 1.0)')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20)),
                ('progresso', models.FloatField(default=0.0, help_text='Percentual de 0 a 100')),
                ('topicos', models.JSONField(default=list, help_text='Lista de tópicos do edital para este módulo')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='concursos.concurso')),
            ],
            options={
                'verbose_name': 'trilha',
                'verbose_name_plural': 'trilhas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
