# Generated by Django 5.0.4 on 2026-04-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoes', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='trilhas.modulo')),
            ],
            options={
                'verbose_name': 'quiz gerado',
                'verbose_name_plural': 'quizzes gerados',
            },
        ),
    ]
