# Generated by Django 5.0.4 on 2026-04-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0003_add_quiz_gerado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('respostas', models.JSONField(default=dict, help_text='{"0": "A", "1": "C", ...}')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='trilhas.quizgerado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_tentativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentativa de quiz',
                'verbose_name_plural': 'tentativas de quiz',
                'ordering': ['-criado_em'],
            },
        ),
    ]
