# Generated by Django 5.0.4 on 2026-04-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0004_add_quiz_tentativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgerado',
            name='referencia',
            field=models.CharField(blank=True, default='', help_text='Nome do subtópico ou tópico avaliado. Vazio para quiz de módulo.', max_length=300),
        ),
        migrations.AddField(
            model_name='quizgerado',
            name='tipo',
            field=models.CharField(choices=[('subtopico', 'Subtópico'), ('topico', 'Tópico'), ('modulo', 'Módulo')], default='modulo', help_text='Nível do quiz: subtópico isolado, tópico inteiro ou módulo completo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizgerado',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='trilhas.modulo'),
        ),
        migrations.AlterUniqueTogether(
            name='quizgerado',
            unique_together={('modulo', 'tipo', 'referencia')},
        ),
        migrations.CreateModel(
            name='Proficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('subtopico', 'Subtópico'), ('topico', 'Tópico'), ('modulo', 'Módulo')], max_length=20)),
                ('referencia', models.CharField(blank=True, default='', help_text='Nome do subtópico ou tópico. Vazio para nível módulo.', max_length=300)),
                ('melhor_acertos', models.PositiveSmallIntegerField(default=0)),
                ('total_questoes', models.PositiveSmallIntegerField(default=0, help_text='Total de questões do quiz que gerou o melhor score.')),
                ('total_tentativas', models.PositiveSmallIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencias', to='trilhas.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proficiência',
                'verbose_name_plural': 'proficiências',
                'ordering': ['nivel', 'referencia'],
                'unique_together': {('modulo', 'usuario', 'nivel', 'referencia')},
            },
        ),
    ]
