# Generated by Django 5.0.4 on 2026-04-09 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0005_quizgerado_referencia_quizgerado_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LacunaConceitual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.PositiveSmallIntegerField(help_text='Índice (0-based) da questão errada na tentativa.')),
                ('subtopico_ref', models.CharField(help_text='Subtópico ao qual o conceito pertence.', max_length=300)),
                ('conceito', models.CharField(help_text='Nome curto do conceito mal compreendido.', max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacunas', to='trilhas.quiztentativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lacunas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lacuna conceitual',
                'verbose_name_plural': 'lacunas conceituais',
                'ordering': ['subtopico_ref', 'conceito'],
                'unique_together': {('tentativa', 'numero_questao')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.TextField(help_text='Pergunta ou estímulo do flashcard.')),
                ('verso', models.TextField(help_text='Resposta ou explicação do flashcard.')),
                ('acertos_consecutivos', models.PositiveSmallIntegerField(default=0)),
                ('ultima_resposta_em', models.DateTimeField(blank=True, null=True)),
                ('lacuna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='trilhas.lacunaconceitual')),
            ],
            options={
                'verbose_name': 'flashcard',
                'verbose_name_plural': 'flashcards',
            },
        ),
    ]
