# Generated by Django 5.0.4 on 2026-03-19 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=30, unique=True)),
                ('site', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'banca',
                'verbose_name_plural': 'bancas',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgao', models.CharField(max_length=200, verbose_name='órgão')),
                ('cargo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('federal', 'Federal'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('militar', 'Militar')], max_length=20)),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado')], default='previsto', max_length=20)),
                ('vagas', models.PositiveIntegerField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inscricao_ini', models.DateField(blank=True, null=True, verbose_name='início das inscrições')),
                ('inscricao_fim', models.DateField(blank=True, null=True, verbose_name='fim das inscrições')),
                ('edital_url', models.URLField(blank=True, verbose_name='URL do edital')),
                ('edital_texto', models.TextField(blank=True, help_text='Cole aqui o texto extraído do edital. Este campo alimenta a IA para gerar trilhas.', verbose_name='texto do edital')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concursos', to='concursos.banca')),
            ],
            options={
                'verbose_name': 'concurso',
                'verbose_name_plural': 'concursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConcursoSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvo_em', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos_por', to='concursos.concurso')),
            ],
            options={
                'verbose_name': 'concurso salvo',
                'verbose_name_plural': 'concursos salvos',
            },
        ),
    ]
